import { checkUser } from "@/lib/check-user";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

import { Header } from "@/components/header";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from "@clerk/nextjs";
import { currentUser } from "@clerk/nextjs/server";
import { redirect } from "next/navigation";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const user = await checkUser();
	return (
		<ClerkProvider>
			<html lang="pt">
				<body className={cn(geistSans.className, geistMono.className)}>
					{/* <SignedIn> */}
					{/* Conteúdo mostrado apenas para usuários autenticados */}
					{children}
					{/* </SignedIn> */}

					<Toaster />
				</body>
			</html>
		</ClerkProvider>
	);
}
